notifications without shelling out
greyblake/cargo-testify pull request #1
Opened 2017-09-03 20:07 UTC by hoodie

Hi there, awesome tool.
I saw that you check for local tools like notify-send and osascript to produce notifications. There is actually already a crate for that :D 
This is what it would look like.

cheers

2017-09-03 22:18 UTC, greyblake commented
@hoodie Hey, thanks for the pull request!
I've seen that crate, but I was under impression that it does not support Mac, the description says `Send Desktop Notifications on linux and bsd`.

Hm..By some reason the PR breaks the build.

2017-09-03 22:20 UTC, greyblake commented
Tests pass locally for me. 
Looks like `notify-rust` uses dbus

2017-09-03 22:25 UTC, greyblake commented
@hoodie  The version with `notify-rust` shows only `title` without message:

![image](https://user-images.githubusercontent.com/113512/30007087-4af34e88-9107-11e7-9f67-6f6aa7adfa86.png)

2017-09-03 22:26 UTC, greyblake requested changes

2017-09-03 22:26 UTC, greyblake commented on src/reactor.rs
> +                    .summary(report.title())
Looks like we need to set `body` here as well, when `report.detail` is `Some(String)`

2017-09-03 22:40 UTC, hoodie commented
sorry, I didn't check the CI on this PR - I just added the required config to the .travis.yml

2017-09-04 17:49 UTC, merged

2017-09-04 17:49 UTC, greyblake commented
@hoodie  Thank you!)